modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="drstone"
version="1.0.0"
displayName="Dr. Stone: Kingdom of Science"
displayURL="https://discord.gg/TJj3Sk52Jq"
logoFile="logo.png"
credits="NoiiLive, Riichiro Inagaki"
authors="NoiiLive"
description="Adds Dr. Stone Items and Technology into Minecraft"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.drstone]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.drstone]]
    modId="kleidersplayerrenderer"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.drstone]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration